# Generated by Django 4.2.3 on 2023-08-06 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EskizSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Eskiz Email"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=255, verbose_name="Eskiz kabinetidan parol"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nickname (Birlamchi 4546)",
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Callback URL (Ixtiyoriy)"
                    ),
                ),
                (
                    "eskiz_token",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Token (Avtomatik yangilanadi)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="So'ngi yangilanish",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sozlama",
                "verbose_name_plural": "Sozlamalar",
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
                ("message", models.TextField(verbose_name="SMS matni")),
                (
                    "from_name",
                    models.CharField(max_length=255, verbose_name="Qaysi nikdan"),
                ),
                ("status", models.CharField(max_length=10, verbose_name="Holati")),
                (
                    "status_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oxirgi o'zgarish",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Xatolik"),
                ),
                (
                    "from_app",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Qaysi 'app'dan",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS tarixi",
                "verbose_name_plural": "SMSlar tarixi",
            },
        ),
    ]
